package service

import (
	"buf.build/go/protovalidate"
	"context"
	"fmt"
	"log/slog"
	stdhttp "net/http"

	kerrors "github.com/go-kratos/kratos/v3/errors"
	"github.com/go-kratos/kratos/v3/transport"
	khttp "github.com/go-kratos/kratos/v3/transport/http"
	v1 "github.com/tpl-x/kratos/api/helloworld/v1"
	"github.com/tpl-x/kratos/internal/biz"
)

var _ v1.GreeterServiceServer = (*GreeterService)(nil)

// GreeterService is a greeter service.
type GreeterService struct {
	log       *slog.Logger
	uc        *biz.GreeterUseCase
	validator protovalidate.Validator
}

// NewGreeterService new a greeter service.
func NewGreeterService(uc *biz.GreeterUseCase, logger *slog.Logger, validator protovalidate.Validator) *GreeterService {
	return &GreeterService{
		uc:        uc,
		validator: validator,
		log:       logger.With(slog.String("module", "service/greeterService")),
	}
}

// LuckySearch implements helloworld.LuckySearch
func (s *GreeterService) LuckySearch(ctx context.Context, request *v1.LuckySearchRequest) (*v1.LuckySearchResponse, error) {
	if err := s.validator.Validate(request); err != nil {
		s.log.ErrorContext(ctx, "request validate failed", slog.Any("error", err))
		return nil, err
	}
	s.log.InfoContext(ctx, "validation succeeded")

	keyword := request.GetKeyword()
	redirectTo := fmt.Sprintf("https://www.google.com/search?q=%s", keyword)
	resp := &v1.LuckySearchResponse{
		RedirectTo: redirectTo,
		StatusCode: int32(stdhttp.StatusFound),
	}
	if tr, ok := transport.FromServerContext(ctx); ok && tr.Kind() == transport.KindHTTP {
		return nil, khttp.NewRedirect(redirectTo, stdhttp.StatusFound)
	}
	return resp, nil
}

// GetShelf demonstrates using the AIP resource-name helper generated by protoc-gen-go-aip.
func (s *GreeterService) GetShelf(ctx context.Context, request *v1.GetShelfRequest) (*v1.GetShelfResponse, error) {
	if err := s.validator.Validate(request); err != nil {
		s.log.ErrorContext(ctx, "request validate failed", slog.Any("error", err))
		return nil, err
	}

	var name v1.ShelfResourceName
	if err := name.UnmarshalString(request.GetName()); err != nil {
		s.log.ErrorContext(ctx, "invalid shelf resource name", slog.Any("error", err))
		return nil, kerrors.BadRequest("INVALID_RESOURCE_NAME", "invalid shelf resource name")
	}

	return &v1.GetShelfResponse{
		Shelf: &v1.Shelf{
			Name:        name.String(),
			DisplayName: fmt.Sprintf("Shelf %s", name.Shelf),
		},
	}, nil
}

// SayHello implements helloworld.GreeterServer.
func (s *GreeterService) SayHello(ctx context.Context, request *v1.SayHelloRequest) (*v1.SayHelloResponse, error) {
	if err := s.validator.Validate(request); err != nil {
		s.log.ErrorContext(ctx, "request validate failed", slog.Any("error", err))
		return nil, err
	}
	s.log.InfoContext(ctx, "validation succeeded")
	g, err := s.uc.CreateGreeter(ctx, &biz.Greeter{Hello: request.Name})
	if err != nil {
		return nil, err
	}
	return &v1.SayHelloResponse{Message: "Hello " + g.Hello}, nil
}
