// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: helloworld/v1/greeter.proto

package v1

import (
	_ "buf.build/go/protovalidate"
	_ "github.com/google/gnostic/openapiv3"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Shelf demonstrates google.api.resource annotations for protoc-gen-go-aip.
type Shelf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                  // the AIP resource name, for example shelves/default
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"` // the shelf display name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shelf) Reset() {
	*x = Shelf{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shelf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shelf) ProtoMessage() {}

func (x *Shelf) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shelf.ProtoReflect.Descriptor instead.
func (*Shelf) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{0}
}

func (x *Shelf) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Shelf) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

// The request message containing the shelf resource name.
type GetShelfRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // the AIP resource name, for example shelves/default
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShelfRequest) Reset() {
	*x = GetShelfRequest{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShelfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShelfRequest) ProtoMessage() {}

func (x *GetShelfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShelfRequest.ProtoReflect.Descriptor instead.
func (*GetShelfRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{1}
}

func (x *GetShelfRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The response message containing the shelf.
type GetShelfResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shelf         *Shelf                 `protobuf:"bytes,1,opt,name=shelf,proto3" json:"shelf,omitempty"` // the requested shelf
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShelfResponse) Reset() {
	*x = GetShelfResponse{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShelfResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShelfResponse) ProtoMessage() {}

func (x *GetShelfResponse) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShelfResponse.ProtoReflect.Descriptor instead.
func (*GetShelfResponse) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{2}
}

func (x *GetShelfResponse) GetShelf() *Shelf {
	if x != nil {
		return x.Shelf
	}
	return nil
}

// The request message containing the user's name.
type SayHelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // the name to greet
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloRequest) Reset() {
	*x = SayHelloRequest{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloRequest) ProtoMessage() {}

func (x *SayHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloRequest.ProtoReflect.Descriptor instead.
func (*SayHelloRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{3}
}

func (x *SayHelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The response message containing the greetings
type SayHelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // the message from server
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayHelloResponse) Reset() {
	*x = SayHelloResponse{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayHelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayHelloResponse) ProtoMessage() {}

func (x *SayHelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayHelloResponse.ProtoReflect.Descriptor instead.
func (*SayHelloResponse) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{4}
}

func (x *SayHelloResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// the request message containing the search keywords for search
type LuckySearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LuckySearchRequest) Reset() {
	*x = LuckySearchRequest{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LuckySearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LuckySearchRequest) ProtoMessage() {}

func (x *LuckySearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LuckySearchRequest.ProtoReflect.Descriptor instead.
func (*LuckySearchRequest) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{5}
}

func (x *LuckySearchRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

// The response message containing the target to redirect to and status code
type LuckySearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RedirectTo    string                 `protobuf:"bytes,1,opt,name=redirect_to,json=redirectTo,proto3" json:"redirect_to,omitempty"`
	StatusCode    int32                  `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LuckySearchResponse) Reset() {
	*x = LuckySearchResponse{}
	mi := &file_helloworld_v1_greeter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LuckySearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LuckySearchResponse) ProtoMessage() {}

func (x *LuckySearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_helloworld_v1_greeter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LuckySearchResponse.ProtoReflect.Descriptor instead.
func (*LuckySearchResponse) Descriptor() ([]byte, []int) {
	return file_helloworld_v1_greeter_proto_rawDescGZIP(), []int{6}
}

func (x *LuckySearchResponse) GetRedirectTo() string {
	if x != nil {
		return x.RedirectTo
	}
	return ""
}

func (x *LuckySearchResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

var File_helloworld_v1_greeter_proto protoreflect.FileDescriptor

const file_helloworld_v1_greeter_proto_rawDesc = "" +
	"\n" +
	"\x1bhelloworld/v1/greeter.proto\x12\rhelloworld.v1\x1a\x1bbuf/validate/validate.proto\x1a$gnostic/openapi/v3/annotations.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x19google/api/resource.proto\"\x9a\x01\n" +
	"\x05Shelf\x12\x1e\n" +
	"\x04name\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x01R\x04name\x12*\n" +
	"\fdisplay_name\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x18@R\vdisplayName:E\xeaAB\n" +
	"\x1fhelloworld.googleapis.com/Shelf\x12\x0fshelves/{shelf}*\ashelves2\x05shelf\"B\n" +
	"\x0fGetShelfRequest\x12/\n" +
	"\x04name\x18\x01 \x01(\tB\x1b\xbaH\x18r\x16\x10\x01\x18\x80\x012\x0f^shelves/[^/]+$R\x04name\">\n" +
	"\x10GetShelfResponse\x12*\n" +
	"\x05shelf\x18\x01 \x01(\v2\x14.helloworld.v1.ShelfR\x05shelf\"0\n" +
	"\x0fSayHelloRequest\x12\x1d\n" +
	"\x04name\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x02\x180R\x04name\",\n" +
	"\x10SayHelloResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"7\n" +
	"\x12LuckySearchRequest\x12!\n" +
	"\akeyword\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x02R\akeyword\"m\n" +
	"\x13LuckySearchResponse\x12)\n" +
	"\vredirect_to\x18\x01 \x01(\tB\b\xbaH\x05r\x03\x88\x01\x01R\n" +
	"redirectTo\x12+\n" +
	"\vstatus_code\x18\x02 \x01(\x05B\n" +
	"\xbaH\a\x1a\x05\x18\xd7\x04(dR\n" +
	"statusCode2\xec\x04\n" +
	"\x0eGreeterService\x12\xc0\x01\n" +
	"\bSayHello\x12\x1e.helloworld.v1.SayHelloRequest\x1a\x1f.helloworld.v1.SayHelloResponse\"s\xbaGV\x12\x16say hello api function\x1a1demo interface to say hello to the requested user*\tsay hello\x82\xd3\xe4\x93\x02\x14\x12\x12/helloworld/{name}\x12\xcc\x01\n" +
	"\vLuckySearch\x12!.helloworld.v1.LuckySearchRequest\x1a\".helloworld.v1.LuckySearchResponse\"v\xbaGZ\x12\x19lucky search api function\x1a/demo interface to search  keyword with redirect*\flucky search\x82\xd3\xe4\x93\x02\x13\x12\x11/search/{keyword}\x12\xc7\x01\n" +
	"\bGetShelf\x12\x1e.helloworld.v1.GetShelfRequest\x1a\x1f.helloworld.v1.GetShelfResponse\"z\xbaG[\x12\x16get shelf api function\x1a6demo interface to get a shelf by its AIP resource name*\tget shelf\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/{name=shelves/*}B\x94\x03\xbaG\xec\x01\x12^\n" +
	"\x14Kratos Demo document\x12\x14Kratos Demo document\")\n" +
	"\x04czyt\x12\x11https://czyt.tech\x1a\x0eroot@czyt.tech2\x051.0.0\x1a)\n" +
	"\x15http://localhost:8000\x12\x10Local dev server\x1a,\n" +
	"\x17https://api.example.com\x12\x11Production server\x1a1\n" +
	"\x1fhttps://staging-api.example.com\x12\x0eStaging server\n" +
	"\x11com.helloworld.v1B\fGreeterProtoP\x01Z,github.com/tpl-x/kratos/api/helloworld/v1;v1\xa2\x02\x03HXX\xaa\x02\rHelloworld.V1\xca\x02\rHelloworld\\V1\xe2\x02\x19Helloworld\\V1\\GPBMetadata\xea\x02\x0eHelloworld::V1b\x06proto3"

var (
	file_helloworld_v1_greeter_proto_rawDescOnce sync.Once
	file_helloworld_v1_greeter_proto_rawDescData []byte
)

func file_helloworld_v1_greeter_proto_rawDescGZIP() []byte {
	file_helloworld_v1_greeter_proto_rawDescOnce.Do(func() {
		file_helloworld_v1_greeter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_helloworld_v1_greeter_proto_rawDesc), len(file_helloworld_v1_greeter_proto_rawDesc)))
	})
	return file_helloworld_v1_greeter_proto_rawDescData
}

var file_helloworld_v1_greeter_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_helloworld_v1_greeter_proto_goTypes = []any{
	(*Shelf)(nil),               // 0: helloworld.v1.Shelf
	(*GetShelfRequest)(nil),     // 1: helloworld.v1.GetShelfRequest
	(*GetShelfResponse)(nil),    // 2: helloworld.v1.GetShelfResponse
	(*SayHelloRequest)(nil),     // 3: helloworld.v1.SayHelloRequest
	(*SayHelloResponse)(nil),    // 4: helloworld.v1.SayHelloResponse
	(*LuckySearchRequest)(nil),  // 5: helloworld.v1.LuckySearchRequest
	(*LuckySearchResponse)(nil), // 6: helloworld.v1.LuckySearchResponse
}
var file_helloworld_v1_greeter_proto_depIdxs = []int32{
	0, // 0: helloworld.v1.GetShelfResponse.shelf:type_name -> helloworld.v1.Shelf
	3, // 1: helloworld.v1.GreeterService.SayHello:input_type -> helloworld.v1.SayHelloRequest
	5, // 2: helloworld.v1.GreeterService.LuckySearch:input_type -> helloworld.v1.LuckySearchRequest
	1, // 3: helloworld.v1.GreeterService.GetShelf:input_type -> helloworld.v1.GetShelfRequest
	4, // 4: helloworld.v1.GreeterService.SayHello:output_type -> helloworld.v1.SayHelloResponse
	6, // 5: helloworld.v1.GreeterService.LuckySearch:output_type -> helloworld.v1.LuckySearchResponse
	2, // 6: helloworld.v1.GreeterService.GetShelf:output_type -> helloworld.v1.GetShelfResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_helloworld_v1_greeter_proto_init() }
func file_helloworld_v1_greeter_proto_init() {
	if File_helloworld_v1_greeter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_helloworld_v1_greeter_proto_rawDesc), len(file_helloworld_v1_greeter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_helloworld_v1_greeter_proto_goTypes,
		DependencyIndexes: file_helloworld_v1_greeter_proto_depIdxs,
		MessageInfos:      file_helloworld_v1_greeter_proto_msgTypes,
	}.Build()
	File_helloworld_v1_greeter_proto = out.File
	file_helloworld_v1_greeter_proto_goTypes = nil
	file_helloworld_v1_greeter_proto_depIdxs = nil
}
