// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v3.0.0
// - protoc             (unknown)
// source: helloworld/v1/greeter.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationGreeterServiceGetShelf = "/helloworld.v1.GreeterService/GetShelf"
const OperationGreeterServiceLuckySearch = "/helloworld.v1.GreeterService/LuckySearch"
const OperationGreeterServiceSayHello = "/helloworld.v1.GreeterService/SayHello"

type GreeterServiceHTTPServer interface {
	// GetShelf Gets a shelf by its AIP resource name.
	GetShelf(context.Context, *GetShelfRequest) (*GetShelfResponse, error)
	// LuckySearch Simple Google search by Redirect with keywords
	LuckySearch(context.Context, *LuckySearchRequest) (*LuckySearchResponse, error)
	// SayHello Sends a greeting
	SayHello(context.Context, *SayHelloRequest) (*SayHelloResponse, error)
}

func RegisterGreeterServiceHTTPServer(s *http.Server, srv GreeterServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/helloworld/{name}", _GreeterService_SayHello0_HTTP_Handler(srv))
	r.Handle("GET", "/search/{keyword}", _GreeterService_LuckySearch0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/{name:shelves/[^/]+}", _GreeterService_GetShelf0_HTTP_Handler(srv))
}

func _GreeterService_SayHello0_HTTP_Handler(srv GreeterServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SayHelloRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGreeterServiceSayHello)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SayHello(ctx, req.(*SayHelloRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SayHelloResponse)
		return ctx.Result(200, reply)
	}
}

func _GreeterService_LuckySearch0_HTTP_Handler(srv GreeterServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LuckySearchRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGreeterServiceLuckySearch)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.LuckySearch(ctx, req.(*LuckySearchRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LuckySearchResponse)
		return ctx.Result(200, reply)
	}
}

func _GreeterService_GetShelf0_HTTP_Handler(srv GreeterServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetShelfRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGreeterServiceGetShelf)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetShelf(ctx, req.(*GetShelfRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetShelfResponse)
		return ctx.Result(200, reply)
	}
}

type GreeterServiceHTTPClient interface {
	// GetShelf Gets a shelf by its AIP resource name.
	GetShelf(ctx context.Context, req *GetShelfRequest, opts ...http.CallOption) (rsp *GetShelfResponse, err error)
	// LuckySearch Simple Google search by Redirect with keywords
	LuckySearch(ctx context.Context, req *LuckySearchRequest, opts ...http.CallOption) (rsp *LuckySearchResponse, err error)
	// SayHello Sends a greeting
	SayHello(ctx context.Context, req *SayHelloRequest, opts ...http.CallOption) (rsp *SayHelloResponse, err error)
}

type GreeterServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewGreeterServiceHTTPClient(client *http.Client) GreeterServiceHTTPClient {
	return &GreeterServiceHTTPClientImpl{client}
}

// GetShelf Gets a shelf by its AIP resource name.
func (c *GreeterServiceHTTPClientImpl) GetShelf(ctx context.Context, in *GetShelfRequest, opts ...http.CallOption) (*GetShelfResponse, error) {
	var out GetShelfResponse
	pattern := "/v1/{name=shelves/*}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationGreeterServiceGetShelf),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// LuckySearch Simple Google search by Redirect with keywords
func (c *GreeterServiceHTTPClientImpl) LuckySearch(ctx context.Context, in *LuckySearchRequest, opts ...http.CallOption) (*LuckySearchResponse, error) {
	var out LuckySearchResponse
	pattern := "/search/{keyword}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationGreeterServiceLuckySearch),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SayHello Sends a greeting
func (c *GreeterServiceHTTPClientImpl) SayHello(ctx context.Context, in *SayHelloRequest, opts ...http.CallOption) (*SayHelloResponse, error) {
	var out SayHelloResponse
	pattern := "/helloworld/{name}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationGreeterServiceSayHello),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
